name: Commit Message Lint

on:
  push:

jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      # Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v4

      # Set up Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      # Install dependencies
      - name: Install Dependencies
        run: npm install

      # Run Commitlint
      - name: Run Commitlint
        run: npx --no-install commitlint --from=HEAD~10 --to=HEAD
